## The code below implements a matrix with cached inverse solutions.

## The main idea is to buffer the result of the first computation 
## of the inverse within the matrix generated by makeCacheMatrix and
## to return the result if it is available instead of running the 
## solve code again.

## The makeCacheMatrix function generates a matrix that allows for
## the storage of an inverse of itself. Once this is computed, the
## result of the computation is returned directly.

makeCacheMatrix <- function(x = matrix()) {
        invmatrix <- NULL
        set <- function(y) {
                x <<- y
                invmatrix <<- NULL
        }
        get <- function() x
        setinvmatrix <- function(inv) invmatrix <<- inv
        getinvmatrix <- function() invmatrix
        list(set = set, get = get,
             setinvmatrix = setinvmatrix,
             getinvmatrix = getinvmatrix)
}


## The cacheSolve function returns a matrix that is the inverse of 'x'.
## A computation is performed only when needed. If there is a cached 
## copy of the inverse, it will be returned directly.

cacheSolve <- function(x, ...) {
        invmatrix <- x$getinvmatrix()
        if(!is.null(invmatrix)) {
                message("getting cached data")
                return(invmatrix)
        }
        data <- x$get()
        invmatrix <- solve(data, ...)
        x$setinvmatrix(invmatrix)
        invmatrix
}
